Nikita/dev
LucidtechAI/las-sdk-net pull request #18
Opened 2021-02-05 12:30 UTC by krigar1184

2021-02-05 13:24 UTC, magnurud requested changes

2021-02-05 13:24 UTC, magnurud commented on Lucidtech/Lucidtech.csproj
> +    <TargetFrameworks>netstandard20</TargetFrameworks>
I believe we still want to support the existing frameworks.

2021-02-05 13:24 UTC, magnurud commented on Test/Test.cs
> +                status,
Status can still be a list of strings, so this should still be tested IMO.

2021-02-05 13:24 UTC, magnurud commented on Lucidtech/Las/Client.cs
> +            string? status = null,
Status can be a list of several statuses or a single status.

2021-02-05 13:24 UTC, magnurud commented on Lucidtech/Las/Client.cs
> +                {"executionId", executionIds},
Does this work? will the query-parameters be appended as expected? 
`?executionId=a&executionId=b....`

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <summary>Creates an asset handle, calls the POST /assets endpoint.</summary>
Can exclude the word 'handle' here I think

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// Create a document handle for a jpeg image
This sounds like documentation from /documents?

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// Posting ground truth means posting the ground truth data for the particular document.
Maybe 'post' is a bit misleading here, should we change it to 'Update ground truth for the document' or something similar?

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <summary>Updates an secret, calls the PATCH /secrets/secretId endpoint.</summary>
an secret -> a secret

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <summary>Creates an secret handle, calls the POST /secrets endpoint.</summary>
Create a secret?

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// var response = client.CreateTransition(inputSchema, outputSchema, parameters: params);
missing transitionType in example call

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
>              string transitionType,
Should this be an enum?

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <param name="order">Order of the executions: "ascending" | "descending"</param>
Should this be an enum?

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <param name="status">Status to filter by</param>
Should this be an enum?

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <param name="statuses">List of execution statuses to filter by</param>
param called 'statuses' here, but 'status' in actual function

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        ///     avatar (base64-encoded image)
Are we a bit inconsisten in how we name optional params to a function?
attributes
optionalParams
etc

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +            string? status = null,
status or statuses?

2021-02-05 13:45 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <param name="statuses">Workflow execution status to filter by</param>
status or statuses?

2021-02-09 12:10 UTC, magnurud requested changes

2021-02-09 12:10 UTC, magnurud commented on Lucidtech/Las/Client.cs
> +            List<string>? statuses = null,
Wouldn't it be less code to maintain if the previous method calls this method with its status as a list with one element?

2021-02-09 12:10 UTC, magnurud commented on Lucidtech/Las/Client.cs
> +        /// <param name="status">Workflow execution status to filter by</param>
This method could also call the other one.

2021-02-11 15:03 UTC, magnurud requested changes

2021-02-11 15:03 UTC, magnurud commented on Test/Test.cs
> +        [Ignore("")]
Could you add a short description to why this is ignored?

2021-02-11 15:08 UTC, magnurud approved these changes

2021-02-11 15:08 UTC, merged