5 new endpoints: PATCH appClient, batch, model, GET model, and POST models
LucidtechAI/las-sdk-net pull request #31
Opened 2021-05-21 07:56 UTC by magnurud

2021-05-21 08:37 UTC, tringholm requested changes

2021-05-21 08:37 UTC, tringholm commented on Lucidtech/Las/Client.cs
> +        /// <param name="description>Description of the model</param>
Missing quote

2021-05-21 08:37 UTC, tringholm commented on Lucidtech/Las/Client.cs
> +        /// <param name="description>Description of the model</param>
Missing quote

2021-05-21 08:37 UTC, tringholm commented on Lucidtech/Lucidtech.csproj
> +    <PackageVersion>1.2.1</PackageVersion>
Should the version be 1.3.0? This update includes new non-breaking features, so I'd expect a jump in minor version

2021-05-21 08:41 UTC, augustak requested changes

2021-05-21 08:41 UTC, augustak commented on Lucidtech/Las/Client.cs
>              List<string>? callbackUrls = null,
Missing loginUrls, default_login_url

2021-05-21 08:41 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <param name="description>Description of the model</param>
```suggestion
        /// <param name="description">Description of the model</param>
```

2021-05-21 08:41 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <param name="description>Description of the model</param>
```suggestion
        /// <param name="description">Description of the model</param>
```

2021-05-21 08:41 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <summary>Get information about a specific model, calls the GET /models/{model_id} endpoint.</summary>
```suggestion
        /// <summary>Get information about a specific model, calls the GET /models/{modelId} endpoint.</summary>
```

2021-05-21 08:41 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <param name="attributes">Additional attributes</param>
Missing status param

2021-05-21 08:41 UTC, augustak commented on Lucidtech/Lucidtech.csproj
> +    <PackageVersion>1.2.1</PackageVersion>
```suggestion
    <PackageVersion>1.3.0</PackageVersion>
```

2021-05-21 08:41 UTC, augustak commented on Test/Service.cs
> +                },
Indentation here looks a bit off

2021-05-21 08:41 UTC, augustak commented on Test/Service.cs
> +                {"DueDate", new Dictionary<string, object>(){
Do we need parenthesises?

2021-05-21 08:41 UTC, augustak commented on Test/Service.cs
> +                {"TotalAmount", new Dictionary<string, object>(){
(Foreach Dictionary in code) Do we not want a nice litte whitespace between > and {? Like so:

```suggestion
                {"TotalAmount", new Dictionary<string, object> {
```

2021-05-21 11:37 UTC, augustak commented on Lucidtech/Las/Client.cs
> +        /// <param name="callbackUrls>List of callback urls</param>
```suggestion
        /// <param name="callbackUrls">List of callback urls</param>
```

2021-05-21 11:37 UTC, augustak commented on Test/Service.cs
>          public static Dictionary<string, object> CompletedConfig(){
```suggestion
        public static Dictionary<string, object> CompletedConfig() {
```

2021-05-21 11:37 UTC, augustak commented on Test/Service.cs
>          public static Dictionary<string, object> ErrorConfig(){
```suggestion
        public static Dictionary<string, object> ErrorConfig() {
```

2021-05-21 11:37 UTC, augustak commented on Test/Service.cs
>          public static Dictionary<string, string?> NameAndDescription(string? name, string? description){
```suggestion
        public static Dictionary<string, string?> NameAndDescription(string? name, string? description) {
```

2021-05-21 11:37 UTC, augustak commented on Test/Service.cs
> +        public static Dictionary<string, object> PreprocessConfig(){
```suggestion
        public static Dictionary<string, object> PreprocessConfig() {
```

2021-05-21 11:37 UTC, augustak commented on Test/Service.cs
> +        public static Dictionary<string, object> FieldConfig(){
```suggestion
        public static Dictionary<string, object> FieldConfig() {
```

2021-06-28 10:58 UTC, tringholm approved these changes

2021-06-28 10:58 UTC, augustak approved these changes

2021-06-28 10:59 UTC, merged